services:
  mongodb:
    image: mongo:8
    cpus: 1.0
    mem_limit: 768m
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: betor
      MONGO_INITDB_ROOT_PASSWORD: betor
    healthcheck:
      test: ["CMD-SHELL", "test \"$$(mongosh --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok')\" = \"1\""]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express:1
    cpus: 0.25
    mem_limit: 128m
    ports:
      - 8081:8081
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: betor
      ME_CONFIG_MONGODB_ADMINPASSWORD: betor
      ME_CONFIG_MONGODB_URL: mongodb://betor:betor@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:8
    cpus: 0.25
    mem_limit: 128m
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - type: bind
        source: E:/Betor/redis
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  influxdb:
    image: influxdb:3-core
    cpus: 0.75
    mem_limit: 512m
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - type: bind
        source: E:/Betor/influxdb/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: E:/Betor/influxdb/plugins
        target: /var/lib/influxdb3/plugins

  grafana:
    image: grafana/grafana:latest
    cpus: 0.5
    mem_limit: 256m
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=betor

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    cpus: 0.75
    mem_limit: 512m

  celery-worker-items:
    image: dougppaz/betor
    cpus: 0.75
    mem_limit: 512m
    build:
      context: .
    command: ["celery", "-A", "betor.celery.app", "worker", "-Q", "items", "--concurrency=2"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .docker.env


  celery-worker-api-requests:
    image: dougppaz/betor
    cpus: 0.5
    mem_limit: 384m
    build:
      context: .
    command: ["celery", "-A", "betor.celery.app", "worker", "-Q", "api-requests", "--concurrency=2"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .docker.env

  celery-worker-torrents:
    image: dougppaz/betor
    cpus: 0.5
    mem_limit: 384m
    build:
      context: .
    command: ["celery", "-A", "betor.celery.app", "worker", "-Q", "torrents", "--concurrency=1"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .docker.env
    ports:
      - 6881:6881
    volumes:
      - type: bind
        source: E:/Betor/torrents
        target: /torrents

  celery-flower:
    image: dougppaz/betor
    cpus: 0.25
    mem_limit: 192m
    build:
      context: .
    command: ["celery", "-A", "betor.celery.app", "flower", "--persistent=True", "--db=/var/lib/flower/flower"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .docker.env
    ports:
      - 5555:5555
    volumes:
      - type: bind
        source: E:/Betor/flower
        target: /var/lib/flower

  scrapyd:
    image: dougppaz/betor
    cpus: 0.75
    mem_limit: 512m
    build:
      context: .
    command: ["scrapyd"]
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      flaresolverr:
        condition: service_started
      influxdb:
        condition: service_started
    env_file:
      - .docker.env
    ports:
      - 6800:6800

  betor-api:
    image: dougppaz/betor
    cpus: 0.75
    mem_limit: 384m
    build:
      context: .
    command: ["fastapi", "run", "betor/api/app.py"]
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      scrapyd:
        condition: service_started
    env_file:
      - .docker.env
    ports:
      - 8000:8000
    volumes:
      - items-data:/items-data

  nginx:
    image: nginx:latest
    cpus: 0.25
    mem_limit: 64m
    ports:
      - 8001:80
    volumes:
      - torrents:/usr/share/nginx/html/torrents
      - items-data:/usr/share/nginx/html/items-data

volumes:
  grafana-data: {}
  torrents: {}
  items-data: {}
