services:
  redis:
    image: redis:8
    cpus: 0.25
    mem_limit: 128m
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    cpus: 0.75
    mem_limit: 512m

  celery-worker-items:
    image: dougppaz/betor
    cpus: 0.75
    mem_limit: 512m
    build:
      context: .
    command: ["celery", "-A", "betor.celery.app", "worker", "-Q", "items", "--concurrency=2"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .docker.env

  celery-worker-api-requests:
    image: dougppaz/betor
    cpus: 0.5
    mem_limit: 384m
    build:
      context: .
    command: ["celery", "-A", "betor.celery.app", "worker", "-Q", "api-requests", "--concurrency=2"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .docker.env

  celery-worker-torrents:
    image: dougppaz/betor
    cpus: 0.5
    mem_limit: 384m
    build:
      context: .
    command: ["celery", "-A", "betor.celery.app", "worker", "-Q", "torrents", "--concurrency=1"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .docker.env
    ports:
      - 6881:6881
    volumes:
      - torrents:/torrents

  celery-flower:
    image: dougppaz/betor
    cpus: 0.25
    mem_limit: 192m
    build:
      context: .
    command: ["celery", "-A", "betor.celery.app", "flower", "--persistent=True", "--db=/var/lib/flower/flower"]
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .docker.env
    ports:
      - 5555:5555
    volumes:
      - flower-data:/var/lib/flower

  scrapyd:
    image: dougppaz/betor
    cpus: 0.75
    mem_limit: 512m
    build:
      context: .
    command: ["scrapyd"]
    depends_on:
      redis:
        condition: service_healthy
      flaresolverr:
        condition: service_started
    env_file:
      - .docker.env
    ports:
      - 6800:6800

  betor-api:
    image: dougppaz/betor
    cpus: 0.75
    mem_limit: 384m
    build:
      context: .
    command: ["fastapi", "run", "betor/api/app.py"]
    depends_on:
      redis:
        condition: service_healthy
      scrapyd:
        condition: service_started
    env_file:
      - .docker.env
    ports:
      - 8000:8000
    volumes:
      - items-data:/items-data

  nginx:
    image: nginx:latest
    cpus: 0.25
    mem_limit: 64m
    ports:
      - 8001:80
    volumes:
      - torrents:/usr/share/nginx/html/torrents
      - items-data:/usr/share/nginx/html/items-data

volumes:
  redis-data: {}
  torrents: {}
  items-data: {}
  flower-data: {}
